feat(BUX-240): code standards for frontend applications
4chain-ag/code-standards-bsv pull request #10
Opened 2023-10-06 09:13 UTC by kuba-4chain

# Pull Request Checklist

- [x] 📖 I created my PR using provided  : [CODE_STANDARDS](https://github.com/4chain-ag/code-standards-bsv/blob/main/.github/CODE_STANDARDS.md)
- [x] 📖 I have read the short Code of Conduct: [CODE_OF_CONDUCT](https://github.com/4chain-ag/code-standards-bsv/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] 🏠 I tested my changes locally.
- [ ] ✅ I have provided tests for my changes.
- [x] 📝 I have used conventional commits.
- [x] 📗 I have updated any related documentation.
- [x] 💾 PR was issued based on the Github or Jira issue.

2023-10-06 13:37 UTC, mwilkosinski requested changes

2023-10-06 13:37 UTC, mwilkosinski commented on .github/CODE_STANDARDS.md
> +```
- When possible, use default values of a given type rather than `null` or `undefined` values.

```ts
const person = {
  firstName: "Bill",
  lastName: null,  // 🟥
  lastName: "",    // ✅
}
```

- If for some reason a default value cannot be assigned or it is impractical to assign a default value, assign a `null` value rather than an `undefined` value

```ts
const person = {
  firstName: "Bill",
  address: undefined, // 🟥
  address: null,      // ✅
}
```

- When code you have no control over (external library) or JavaScript itself may return `undefined`, convert it to `null` (or preferably to a default value if possible)

```ts
const found = arr.find((item) => item > 5);         // 🟥
const found = arr.find((item) => item > 5) ?? null; // ✅
```

2023-10-06 13:37 UTC, mwilkosinski commented on .github/CODE_STANDARDS.md
> +- Use `undefined` instead of `null` whenever possible.
Remove this in favour of the three rules in my other comment:

> * When possible, use default values of a given type rather than null or undefined values
> * If for some reason a default value cannot be assigned or it is impractical to assign a default value, assign a null value rather than an undefined value
> * When code you have no control over (external library) or JavaScript itself may return undefined, convert it to null (or preferably to a default value if possible)

2023-10-06 13:37 UTC, mwilkosinski commented on .github/CODE_STANDARDS.md
> +}
In code examples, use TypeScript `interface` instead of `type` when declaring types for objects:

```
interface MyComponentProps {
  setName: any; // 🟥
  setName: React.Dispatch<React.SetStateAction<string>>; // ✅
}
```

2023-10-06 13:37 UTC, mwilkosinski commented on .github/CODE_STANDARDS.md
> +- When writing html/jsx/tsx, use proper html tags, suitable for a given component.
Maybe add the word "semantic":

- When writing html/jsx/tsx, use proper semantic html tags, suitable for a given component.

2023-10-06 17:50 UTC, mwilkosinski approved these changes

2023-10-06 17:52 UTC, mwilkosinski approved these changes

2023-10-10 06:55 UTC, wregulski approved these changes

2023-10-11 10:52 UTC, merged